"use client";
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {Activity,ArrowLeft,ArrowUpRight,BookOpen,Check,ChevronRight,Copy,FileJson2,FlaskConical,Info,LoaderCircle,TriangleAlert,Upload} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Alert,AlertDescription} from '@/components/ui/alert';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {parseReplay,replayTotals,waferState,alertNames,formatObservation,replayChart,investigationText,type Replay,type ReplayAlert} from '@/lib/rtdi/replay';
import './replay.css';
import {ThemeSelector} from '@/components/theme-controls';
import {waferEvaluation,replaySelection} from '@/lib/rtdi/ui-presentation';
const colors=['var(--chart-1)','var(--chart-2)','var(--chart-3)','var(--chart-4)','var(--chart-5)'];
function EvidencePlot({alert}:{alert:ReplayAlert}){
 const lines=replayChart(alert);const values=lines.flatMap(l=>l.values);if(!values.length)return <div className="no-chart">此證據未提供序列，不繪製推測曲線。</div>;
 const yieldMode=alert.kind==='low_yield';const reference=yieldMode?alert.reference:alert.baseline?.mean;
 const all=[...values,...(reference===undefined?[]:[reference])];const low=all.reduce((m,v)=>Math.min(m,v),Infinity),high=all.reduce((m,v)=>Math.max(m,v),-Infinity);const padding=Math.max((high-low)*.13,.001);
 const min=yieldMode?0:low-padding,max=yieldMode?Math.max(1,high):high+padding;
 const y=(v:number)=>215-(v-min)/(max-min)*180;const count=Math.max(...lines.map(l=>l.values.length));const x=(i:number)=>60+i/Math.max(count-1,1)*560;
 return <div className="replay-plot"><div className="plot-caption"><strong>{yieldMode?'累積良率':'各 site 的測量序列'}</strong><span>{yieldMode?'百分比':'原始數值 · 單位未確認'}</span></div><svg viewBox="0 0 650 260" role="img" aria-label={`${alertNames[alert.kind]}，${lines.map(l=>l.name).join('、')}；橫軸為序列索引，不是時間。`}>
 {[0,1,2,3,4].map(i=>{const value=min+(max-min)*i/4;return <g key={i}><path d={`M60 ${y(value)}H620`} stroke="var(--border)"/><text x="49" y={y(value)+4} textAnchor="end">{yieldMode?`${(value*100).toFixed(0)}%`:value.toFixed(2)}</text></g>})}
 {reference!==undefined&&<g><path d={`M60 ${y(reference)}H620`} stroke="var(--muted-foreground)" strokeDasharray="5 5"/><text x="620" y={y(reference)-7} textAnchor="end">{yieldMode?'良率門檻':'基準均值'} {yieldMode?`${(reference*100).toFixed(0)}%`:reference.toFixed(3)}</text></g>}
 {lines.map((line,k)=><g key={line.name}><path d={line.values.map((v,i)=>`${i?'L':'M'}${x(i)} ${y(v)}`).join(' ')} stroke={colors[k%colors.length]} strokeWidth="2.4" fill="none" strokeLinejoin="round"/>{line.values.map((v,i)=><circle key={i} cx={x(i)} cy={y(v)} r={count>100?1:2} fill={colors[k%colors.length]}><title>{line.name} · 索引 {i+1}：{v}</title></circle>)}</g>)}
 {[0,Math.floor((count-1)/2),count-1].map((i,k)=><text key={k} x={x(i)} y="239" textAnchor="middle">{i+1}</text>)}
 </svg><div className="plot-legend">{lines.map((l,i)=><span key={l.name}><i style={{background:colors[i%colors.length]}}/>{l.name}</span>)}<span className="axis-note">{yieldMode?'完成 device 順序':'各 site 內樣本順序'} · 無時間戳</span></div></div>;
}
export default function ReplayPage(){
 const [data,setData]=useState<Replay|null>(null),[source,setSource]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [waferId,setWaferId]=useState('1'),[alertIndex,setAlertIndex]=useState(0),[filter,setFilter]=useState('all'),[copied,setCopied]=useState(false);
 const [demoStep,setDemoStep]=useState(-1);const fileRef=useRef<HTMLInputElement>(null);const requestSeq=useRef(0);
 function accept(input:unknown,name:string){const parsed=parseReplay(input);setData(parsed);setSource(name);setWaferId(parsed.wafers[0].wafer);setAlertIndex(0);setFilter('all');setError('');setCopied(false);setDemoStep(-1);}
 async function loadProject(){const n=++requestSeq.current;setLoading(true);setError('');try{const r=await fetch('/replay/summary.json');if(!r.ok)throw Error('讀取專案重播失敗。');const value=await r.json();if(n===requestSeq.current)accept(value,'專案快照 · results/replay/summary.json');}catch{if(n===requestSeq.current)setError('無法載入專案快照。可重試或匯入 summary.json。');}finally{if(n===requestSeq.current)setLoading(false);}}
 useEffect(()=>{void loadProject();return()=>{requestSeq.current++;};},[]);
 async function importFile(file:File){const n=++requestSeq.current;setLoading(true);setError('');try{if(file.size>5*1024*1024)throw Error('檔案超過 5 MB，請提供摘要而非原始測量檔。');const value=JSON.parse(await file.text());if(n===requestSeq.current)accept(value,`本機匯入 · ${file.name}`);}catch(err){if(n===requestSeq.current)setError(err instanceof Error&&err.message.startsWith('檔案超過')?err.message:'格式不符：請匯入 grp6 replay summary.json（mode=replay、wafers、validation、limitations）。原有資料保留。');}finally{if(n===requestSeq.current)setLoading(false);}}
 const total=data?replayTotals(data):null;const wafer=data?.wafers.find(w=>w.wafer===waferId);const alert=wafer?.alerts[alertIndex];
 const displayed=data?.wafers.filter(w=>filter==='all'||waferState(w)===filter)??[];
 const demoWafers=['1','3','14','23','25'].filter(id=>data?.wafers.some(w=>w.wafer===id));
 function nextDemo(){if(!demoWafers.length)return;const step=(demoStep+1)%demoWafers.length;setDemoStep(step);setWaferId(demoWafers[step]);setAlertIndex(0);setFilter('all');setCopied(false);}
 return <div className="shell"><header className="topbar"><Link className="brand" href="/"><span className="brandmark"><Activity size={22}/></span> RTDI <span className="brandlight">Insight</span></Link><div className="header-right"><ThemeSelector/><Link className="return-link" href="/"><ArrowLeft size={14}/> 調查工作台</Link><span className="team">G6</span></div></header>
 <main className="workspace replay-workspace"><div className="heading"><div><div className="eyebrow">EVIDENCE REVIEW / REPLAY</div><h1>從一片 wafer，看見異常全貌。</h1><p className="sub">檢視實際重播結果、對照 site 證據，保留每個判斷的限制。</p></div><div className="replay-actions"><Button variant="outline" onClick={()=>fileRef.current?.click()} disabled={loading}><Upload size={16}/> 匯入摘要</Button><Button onClick={nextDemo} disabled={!data||loading||!demoWafers.length}><BookOpen size={16}/>{demoStep<0?'開始 Demo':'下一個案例'}<ChevronRight size={15}/></Button><Input ref={fileRef} type="file" accept=".json,application/json" className="hidden" aria-label="匯入重播摘要 JSON" onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);e.target.value='';}}/></div></div>
 <div className="simulation-banner replay-banner"><FlaskConical size={16}/><span><strong>REPLAY</strong> · 歷史資料重播，不代表即時量產或機台已收到訊息。</span><span className="banner-end">OFFLINE EVIDENCE</span></div>
 <div className="replay-source"><span><FileJson2 size={14}/>{source||(loading?'正在載入專案快照…':'尚未取得摘要')}</span><Button variant="ghost" size="sm" onClick={()=>void loadProject()} disabled={loading}>重新載入專案</Button></div>
 {error&&<Alert variant="destructive" className="inline-error"><TriangleAlert/><AlertDescription>{error}</AlertDescription></Alert>}
 {loading&&<div role="status" className="loading-replay"><LoaderCircle className="spin" size={18}/> 正在驗證重播摘要…</div>}
 {data&&total&&<><div className="stats"><div><span>檢視範圍</span><strong>{data.wafers.length}<small>片 wafer</small></strong><p>{total.devices.toLocaleString()} 顆完成 device</p></div><div><span>觀察到告警</span><strong>{total.alerts}<small>筆證據</small></strong><p>分布在 {total.alertedWafers} 片 wafer</p></div><div><span>資料來源</span><strong>REPLAY</strong><p>已驗證格式的歷史摘要</p></div><div><span>機台接收狀態</span><strong>未提供</strong><p>等待後端提供正式回執</p></div></div>
 <Tabs defaultValue="analysis" className="replay-tabs"><TabsList variant="line"><TabsTrigger value="analysis">Wafer 與異常證據</TabsTrigger><TabsTrigger value="validation">模型驗證</TabsTrigger><TabsTrigger value="limitations">資料限制</TabsTrigger></TabsList>
 <TabsContent value="analysis"><div className="replay-grid"><aside className="panel wafer-panel"><div className="panel-header"><h2>Wafer 總覽</h2><NativeSelect size="sm" aria-label="篩選 wafer" value={filter} onChange={e=>{const value=e.target.value;setFilter(value);const selected=replaySelection(data?.wafers??[],waferId,value);if(selected!==waferId){setWaferId(selected);setAlertIndex(0);setCopied(false);}}}><NativeSelectOption value="all">全部</NativeSelectOption><NativeSelectOption value="alert">有告警</NativeSelectOption><NativeSelectOption value="quiet">未出現告警</NativeSelectOption></NativeSelect></div><p className="wafer-hint">按 wafer 編號排列，非晶圓空間分布圖。</p><div className="wafer-tiles">{displayed.map(w=><button key={w.wafer} className={`wafer-tile ${waferState(w)} ${w.wafer===waferId?'active':''}`} aria-label={`W${w.wafer}，良率 ${(w.yield*100).toFixed(1)}%，${w.alerts.length} 筆告警`} aria-pressed={w.wafer===waferId} onClick={()=>{setWaferId(w.wafer);setAlertIndex(0);setCopied(false);}}><strong>W{w.wafer.padStart(2,'0')}</strong><span>{(w.yield*100).toFixed(1)}%</span><small>{w.alerts.length?`${w.alerts.length} 筆告警`:'未出現告警'}</small></button>)}</div>{!displayed.length&&<p className="wafer-hint">目前沒有符合的 wafer。</p>}<div className="wafer-legend"><span><i/>有告警</span><span>僅按來源告警筆數分組</span></div></aside>
 {wafer&&<section className="panel replay-detail"><div className="panel-header"><h2><Activity size={18}/> W{wafer.wafer} <span className="detail-site-label">/ {wafer.devices} devices</span></h2><span className="mini-label">REPLAY</span></div><div className="wafer-summary"><div><span>累積良率</span><strong>{(wafer.yield*100).toFixed(2)}<small>%</small></strong></div><div><span>資料集標籤</span><strong className="label-value">{alertNames[wafer.expected]??wafer.expected}</strong><p>僅用於評估，不是偵測規則</p></div><div><span>本片告警</span><strong>{wafer.alerts.length}<small>筆</small></strong></div></div>
 {waferEvaluation(wafer)&&<div className="wafer-warning" role="note"><Info size={17}/><span>{waferEvaluation(wafer)}</span></div>}{!wafer.alerts.length?<div className="empty replay-empty"><CircleIcon/><h3>這份摘要未提供本片告警</h3><p>沒有告警不代表已確認正常；請對照來源評估與資料限制。</p></div>:<><div className="alert-selector" role="group" aria-label="選擇異常證據">{wafer.alerts.map((a,i)=><Button key={i} variant={i===alertIndex?'secondary':'ghost'} size="sm" aria-pressed={i===alertIndex} onClick={()=>{setAlertIndex(i);setCopied(false);}}>{alertNames[a.kind]}<span>#{i+1}</span></Button>)}</div>{alert&&<div className="selected-evidence"><div className="selected-title"><h3>{alertNames[alert.kind]} <span>Site {alert.site==='all'?'全部':alert.site}</span></h3><span>完成 {alert.completed_devices} 顆時偵測</span></div><p className="original-message">{alert.message}</p><div className="alert-values"><div><span>觀測值</span><strong>{formatObservation(alert,alert.observed)}</strong></div><div><span>參考值</span><strong>{formatObservation(alert,alert.reference)}</strong></div><div><span>偵測分數</span><strong>{alert.score.toFixed(3)}</strong><small>不是機率</small></div></div><EvidencePlot alert={alert}/><div className="evidence-foot"><span>測項 · {alert.test}</span><span>本地引用 · wafer[{wafer.wafer}].alerts[{alertIndex}]（不是後端 event ID）</span></div><div className="investigation"><div><BookOpen size={16}/><strong>調查建議</strong><span>偵測器原文 · 非 LLM</span></div><p>{alert.suggestion}</p><Button variant="outline" size="sm" onClick={async()=>{try{await navigator.clipboard.writeText(investigationText(wafer.wafer,alert));setCopied(true);}catch{setError('無法使用剪貼簿，請從下方原始證據手動複製。');}}}>{copied?<Check size={14}/>:<Copy size={14}/>} {copied?'已複製摘要':'複製交接摘要'}</Button></div><details className="raw-details"><summary>查看原始 AlertEvidence</summary><pre>{JSON.stringify(alert,null,2)}</pre></details></div>}</>}
 </section>}</div></TabsContent>
 <TabsContent value="validation"><section className="panel model-panel"><div className="panel-header"><h2>六階段模型驗證</h2><span className="mini-label">{data.validation.mode??'驗證方式未提供'}</span></div><div className="model-intro"><h3>使用驗證誤差，與常數 baseline 比較。</h3><p>下表來自 validation.metrics，沒有使用 prediction_in_sample_mae。物理溫度單位尚未確認，數值以 CSV units 顯示。</p></div><div className="table-scroll" tabIndex={0} role="region" aria-label="模型驗證表格，可水平捲動"><table><thead><tr><th>階段</th><th>樣本數</th><th>模型 MAE</th><th>Baseline MAE</th><th>RMSE</th><th>最大誤差</th></tr></thead><tbody>{[1,2,3,4,5,6].map(stage=>{const m=data.validation.metrics[String(stage)];return <tr key={stage}><td><span className="stage-number">0{stage}</span></td><td>{m?.n.toLocaleString()??'未提供'}</td><td className="model-mae">{m?.mae.toFixed(5)??'—'}</td><td>{m?.baseline_mae.toFixed(5)??'—'}</td><td>{m?.rmse.toFixed(5)??'—'}</td><td>{m?.worst_error.toFixed(5)??'—'}</td></tr>})}</tbody></table></div><div className="validation-note"><Info size={17}/><p>這些誤差衡量資料集上的模型表現，不能替代機台實際預測精度、延遲與回覆接收驗收。特徵 coverage 100% 也不代表準確率 100%。</p></div></section></TabsContent>
 <TabsContent value="limitations"><section className="panel limitations-panel"><div className="panel-header"><h2>保留限制，才能正確解讀成果。</h2><span className="mini-label">SOURCE NOTES</span></div><div className="limitations-content"><div className="limit-callout"><TriangleAlert size={20}/><div><strong>重播證據 ≠ 即時驗收</strong><p>缺少 live provenance、完整時間戳及 tester receipt，這個頁面不會顯示機台「已收到」。</p></div></div><h3>摘要檔的原始限制</h3><ul>{data.limitations.map((s,i)=><li key={i}>{s}</li>)}</ul><p className="source-status">來源檔 live_integration 欄位：<code>{data.live_integration}</code>。這是檔案當時紀錄，不代表目前遠端即時狀態。</p><h3>如何繼續調查</h3><p>回到調查工作台可查閱批次證據、預測與回執狀態；離線摘要保留來源當時的限制。這頁匯入只在瀏覽器解析，不會上傳或呼叫 OpenAI。</p></div></section></TabsContent></Tabs>
 <footer><span><FlaskConical size={13}/> {source} · 重新整理會回到專案快照</span><Link href="/">回到調查工作台 <ArrowUpRight size={13}/></Link></footer></>}
 </main></div>;
}
function CircleIcon(){return <div className="empty-icon"><Info size={27}/></div>;}
