"use client";
import {z} from "zod";
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Activity,ArrowUpRight,ArrowRight,Database,Radio,FlaskConical,Search,Layers3,Sparkles,Send,RefreshCw,TriangleAlert,ChevronRight,Unplug,CheckCircle2,Clock3} from 'lucide-react';
import {parseSnapshot,runUrl,commandLabels,type Snapshot} from '@/lib/rtdi/dashboard';
import {predictionRows,predictionLabels} from '@/lib/rtdi/ui-predictions';
import type {UiEdgeRecord as EdgeRecord} from '@/lib/rtdi/ui-wire';
import './dashboard.css';
const names:Record<string,string>={site_imbalance:'Site 不平衡',low_yield:'良率下降',mean_drift_up:'均值上升',mean_drift_down:'均值下降',spread_up:'離散程度上升',spread_down:'離散程度下降'};
const palette=['#187968','#d89a39','#728ee0','#bb7391'];
const number=(n:number|undefined)=>n===undefined?'—':n.toFixed(4);
const observation=(e:EdgeRecord,n:number|undefined)=>n===undefined?'—':e.kind==='low_yield'?`${(n*100).toFixed(2)}%`:number(n);
function Plot({e}:{e:EdgeRecord}){
 const site=Object.entries(e.site_series??{}).filter(([,v])=>v.length);
 const lines=e.kind==='low_yield'?[['累積良率',e.series??[]] as const]:site.length?site:[['觀測序列',e.series??[]] as const];
 const values=lines.flatMap(([,v])=>v);if(!values.length)return <div className="dc-empty"><Activity/><h3>等待序列資料</h3><p>這筆證據尚未提供可繪製的序列。</p></div>;
 const lo=Math.min(...values),hi=Math.max(...values),pad=Math.max((hi-lo)*.15,.001),min=lo-pad,max=hi+pad,count=Math.max(...lines.map(([,v])=>v.length));
 const x=(i:number)=>55+i/Math.max(count-1,1)*570,y=(v:number)=>212-(v-min)/(max-min)*170;
 return <div className="dc-plot"><svg viewBox="0 0 650 255" role="img" aria-label="來源提供的測量序列；橫軸為各 site 已完成裝置順序，不是事件時間">{[0,1,2,3].map(i=>{const v=min+(max-min)*i/3;return <g key={i}><path d={`M55 ${y(v)}H625`} stroke="#e6ebe7" strokeDasharray="3 5"/><text x="44" y={y(v)+4} textAnchor="end">{e.kind==='low_yield'?`${(v*100).toFixed(0)}%`:v.toFixed(2)}</text></g>})}{lines.map(([label,v],j)=><path key={label} d={v.map((a,i)=>`${i?'L':'M'}${x(i)} ${y(a)}`).join(' ')} stroke={palette[j%4]} strokeWidth="2.7" fill="none" strokeLinecap="round" strokeLinejoin="round"/>)}{[0,Math.floor((count-1)/2),count-1].map((i,j)=><text key={j} x={x(i)} y="240" textAnchor="middle">{i+1}</text>)}</svg><div className="dc-legend">{lines.map(([label],i)=><span key={label}><i style={{background:palette[i%4]}}/>{site.length&&e.kind!=='low_yield'?`Site ${label}`:label}</span>)}<span>{site.length&&e.kind!=='low_yield'?'各 site 已完成裝置順序':'已完成裝置順序'} · {e.unit??'單位未確認'}</span></div></div>;
}
function Answer({text}:{text:string}){return <div className="dc-answer">{text.split('\n').map((line,i)=>{const clean=line.replace(/^#{1,6}\s*/,'');return line.startsWith('#')?<h4 key={i}>{clean}</h4>:<p key={i}>{clean.split(/(\*\*.*?\*\*|`[^`]+`)/g).map((part,j)=>part.startsWith('**')?<strong key={j}>{part.slice(2,-2)}</strong>:part.startsWith('`')?<code key={j}>{part.slice(1,-1)}</code>:part)}</p>})}</div>;}
export default function Dashboard(){
 const [run,setRun]=useState('grp6-replay-demo'),[tester,setTester]=useState('grp6-replay');
 const [scope,setScope]=useState<{run:string;tester:string}|null>(null),[data,setData]=useState<Snapshot|null>(null),[status,setStatus]=useState('尚未連線'),[error,setError]=useState('');
 const [selected,setSelected]=useState(''),[search,setSearch]=useState(''),[tab,setTab]=useState('evidence');
 const [question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[chatError,setChatError]=useState('');
 const [messages,setMessages]=useState<{role:string;text:string;refs?:string[];id?:string}[]>([]);
 const [config,setConfig]=useState<{openai_configured:boolean;backend_connected:boolean}|null>(null);
 const generation=useRef(0),cancel=useRef<AbortController|null>(null),stream=useRef<EventSource|null>(null),chatCancel=useRef<AbortController|null>(null),busyRef=useRef(false);
 useEffect(()=>{fetch('/api/config').then(r=>r.json()).then(value=>setConfig(z.object({openai_configured:z.boolean(),backend_connected:z.boolean()}).parse(value))).catch(()=>{});return()=>{generation.current++;cancel.current?.abort();stream.current?.close();chatCancel.current?.abort();};},[]);
 async function connect(){
  if(!run.trim())return;const g=++generation.current;cancel.current?.abort();stream.current?.close();chatCancel.current?.abort();busyRef.current=false;setBusy(false);setMessages([]);setChatError('');setData(null);setScope(null);setError('');setStatus('正在連線');setSelected('');
  const ctrl=new AbortController();cancel.current=ctrl;const chosen={run:run.trim(),tester:tester.trim()};let refreshing=false,dirty=false;
  async function snapshot(){if(refreshing){dirty=true;return;}refreshing=true;try{do{dirty=false;const r=await fetch(runUrl(chosen.run,chosen.tester),{signal:ctrl.signal,cache:'no-store'});const json=await r.json();if(!r.ok)throw Error(z.object({error:z.string()}).safeParse(json).data?.error??`讀取失敗 (${r.status})`);const next=parseSnapshot(json,chosen.run,chosen.tester);if(g!==generation.current)return;chosen.tester=next.run.tester_id;setData(next);setScope({...chosen});}while(dirty);}finally{refreshing=false;}}
  try{await snapshot();if(g!==generation.current)return;setStatus('已取得快照');const es=new EventSource(runUrl(chosen.run,chosen.tester,'/events'));stream.current=es;
   const refresh=()=>{void snapshot().catch(err=>{if(g===generation.current&&err.name!=='AbortError'){setError(err.message);setStatus('快照更新失敗');}});};
   es.addEventListener('ready',()=>{if(g===generation.current){setStatus('事件流已連線');setError('');}refresh();});
   es.addEventListener('edge_event',refresh);es.addEventListener('heartbeat',refresh);
   es.addEventListener('stream_error',()=>{if(g===generation.current)setStatus('事件流中斷 · 等待重連');});
   es.onerror=()=>{if(g===generation.current)setStatus('正在重新連線 · 保留上次資料');};
  }catch(err){if(g===generation.current&&err instanceof Error&&err.name!=='AbortError'){setError(err.message);setStatus('連線失敗');}}
 }
 function disconnect(){generation.current++;cancel.current?.abort();stream.current?.close();chatCancel.current?.abort();busyRef.current=false;setBusy(false);setStatus('已中斷 · 保留上次資料');}
 const evidence=data?.evidence??[],filtered=evidence.filter(e=>`${e.kind} ${e.wafer_id} ${e.message} ${e.test_name} ${e.affected_tests?.join(' ')}`.toLowerCase().includes(search.toLowerCase()));
 const current=evidence.find(e=>e.event_id===selected)??filtered[0];
 async function ask(q:string){if(!scope||!q.trim()||busyRef.current)return;busyRef.current=true;setBusy(true);setChatError('');const g=generation.current,ctrl=new AbortController();chatCancel.current=ctrl;const text=q.trim();setQuestion('');
  try{const r=await fetch(runUrl(scope.run,scope.tester,'/chat'),{method:'POST',headers:{'Content-Type':'application/json'},signal:ctrl.signal,body:JSON.stringify({mode:'openai',question:text,tester_id:scope.tester,incident_id:current?.incident_id,history:messages.slice(-10).map(m=>({role:m.role,content:m.text}))})});const payload=await r.json();if(!r.ok)throw Error(z.object({error:z.string()}).safeParse(payload).data?.error??'AI 調查失敗');const body=z.object({answer:z.string(),evidence_ids:z.array(z.string()).optional(),investigation_id:z.string().nullable().optional()}).parse(payload);if(g===generation.current)setMessages(prev=>[...prev,{role:'user',text},{role:'assistant',text:body.answer,refs:body.evidence_ids,id:body.investigation_id??undefined}]);
  }catch(err){if(g===generation.current&&err instanceof Error&&err.name!=='AbortError'){setChatError(err.message);setQuestion(text);}}finally{if(g===generation.current){busyRef.current=false;setBusy(false);}}
 }
 const predictions=predictionRows(data?.events??[]);
 const source=data?.run.mode==='live'?'LIVE · 來源標記':data?.run.mode==='replay'?'REPLAY · 歷史重播':data?'SIMULATION · 示範':'WAITING FOR DATA';
 return <div className="dc-app"><a className="dc-skip" href="#main-content">跳至主內容</a><aside className="dc-sidebar"><Link className="dc-brand" href="/" aria-label="RTDI Insight 首頁"><span><Activity size={24}/></span><div>RTDI<small>INSIGHT / GRP6</small></div></Link><div className="dc-nav-label">WORKSPACE</div><nav aria-label="主要導覽"><Link className="active" href="/" aria-label="調查工作台" aria-current="page"><Layers3 size={18}/>調查工作台<span>01</span></Link><Link href="/replay" aria-label="重播分析"><Activity size={18}/>重播分析<ArrowUpRight size={14}/></Link><Link href="/sandbox" aria-label="示範沙盒"><FlaskConical size={18}/>示範沙盒<ArrowUpRight size={14}/></Link></nav><div className="dc-side-bottom"><span className="dc-dot"/>GRP6 / LOCAL ENVIRONMENT<p>從觀測到理解，<br/>讓每個判斷都有依據。</p><div className="dc-side-grid" aria-hidden="true">{Array.from({length:32},(_,i)=><i key={i}/>)}</div></div></aside>
 <div className="dc-main"><header className="dc-top"><span>工作區 <ChevronRight size={13}/> 調查工作台</span><div><span className={`dc-dot ${status==='事件流已連線'?'connected':''}`}/>{status}<span className="dc-avatar">G6</span></div></header>
 <main id="main-content"><div className="dc-heading"><div><div className="dc-eyebrow">TEST INTELLIGENCE / 01</div><h1>看見異常，理解原因<span>。</span></h1><p>整合測試證據與 AI 調查，從一筆訊號找到下一步。</p></div><Link className="dc-secondary" href="/replay">探索重播資料 <ArrowUpRight size={16}/></Link></div>
 <form className="dc-connect" onSubmit={e=>{e.preventDefault();void connect();}}><div className="dc-connect-title"><Database size={18}/><div><strong>資料連線</strong><small>選擇要調查的測試批次</small></div></div><label>Run ID<input value={run} onChange={e=>setRun(e.target.value)} required maxLength={120}/></label><label>Tester ID<input value={tester} onChange={e=>setTester(e.target.value)} placeholder="可選，建議指定" maxLength={120}/></label><button className="dc-primary" type="submit"><Radio size={16}/>載入批次</button>{scope&&<button className="dc-icon" type="button" aria-label="中斷事件流" onClick={disconnect}><Unplug size={18}/></button>}</form>
 {error&&<div className="dc-error" role="alert"><TriangleAlert size={18}/>{error}<span>檢查批次識別碼與後端設定後，可重新載入。</span></div>}
 <div className="dc-stats"><div><span>資料來源 <Database size={15}/></span><strong className="dc-source">{data?.run.mode.toUpperCase()??'待連線'}</strong><small>{data?.run.tester_id??'尚未取得批次'}</small></div><div><span>異常事件 <Activity size={15}/></span><strong>{data?String(data.incidents.length).padStart(2,'0'):'—'}<em>incidents</em></strong><small>依後端分析結果呈現</small></div><div><span>證據紀錄 <Layers3 size={15}/></span><strong>{data?String(evidence.length).padStart(2,'0'):'—'}<em>evidence</em></strong><small>{data?`${data.events.length} 筆來源事件`:'等待來源資料'}</small></div><div><span>AI 調查助理 <Sparkles size={15}/></span><strong className="dc-source">{config?.openai_configured?'Ready':'待設定'}</strong><small>{config?.openai_configured?'OpenAI · 送出時啟動調查':'需設定伺服器金鑰'}</small></div></div>
 <div className="dc-section-heading"><h2>證據工作區</h2><span className="dc-source-badge"><i/>{source}</span></div><div className="dc-board"><section className="dc-evidence-panel"><div className="dc-tabbar" role="tablist" aria-label="批次檢視">{[['evidence','異常證據'],['predictions','預測紀錄'],['commands','命令狀態']].map(([id,label])=><button role="tab" id={`tab-${id}`} aria-controls="batch-panel" tabIndex={tab===id?0:-1} aria-selected={tab===id} key={id} onKeyDown={e=>{const ids=["evidence","predictions","commands"];const i=ids.indexOf(id);const next=e.key==="ArrowRight"?ids[(i+1)%3]:e.key==="ArrowLeft"?ids[(i+2)%3]:e.key==="Home"?ids[0]:e.key==="End"?ids[2]:null;if(next){e.preventDefault();setTab(next);document.getElementById(`tab-${next}`)?.focus();}}} onClick={()=>setTab(id)}>{label}</button>)}</div>
 <div role="tabpanel" id="batch-panel" aria-labelledby={`tab-${tab}`}>
 {tab==='evidence'&&<><div className="dc-search"><Search size={16}/><input aria-label="搜尋異常證據" placeholder="搜尋 wafer、測項或異常類型…" value={search} disabled={busy} onChange={e=>{setSearch(e.target.value);setSelected('');setMessages([]);setChatError('');}}/><span>{filtered.length} 筆</span></div><div className="dc-evidence-layout"><div className="dc-event-list">{filtered.map((e,i)=><button key={e.event_id} className={current?.event_id===e.event_id?'selected':''} aria-pressed={current?.event_id===e.event_id} onClick={()=>{setSelected(e.event_id);setMessages([]);setChatError('');}} disabled={busy}><span className="dc-event-number">{String(i+1).padStart(2,'0')}</span><div><strong>{names[e.kind??'']??e.kind??'異常證據'}</strong><small>W{e.wafer_id??'—'} · {e.site_id?`Site ${e.site_id}`:'多 site'}</small></div><ChevronRight size={14}/></button>)}{!filtered.length&&<p className="dc-list-empty">{data?'沒有符合的證據':'連線後顯示事件'}</p>}</div><div className="dc-detail">{current?<><div className="dc-detail-top"><span className="dc-warning">{current.severity??'evidence'}</span><span>WAFER {current.wafer_id??'—'}</span></div><h3>{names[current.kind??'']??current.kind??'異常證據'}</h3><p className="dc-message">{current.message??'來源尚未提供說明'}</p><div className="dc-values"><div><small>觀測值</small><strong>{observation(current,current.current_value)}</strong></div><div><small>參考值</small><strong>{observation(current,current.baseline)}</strong></div><div><small>偵測分數 · 非機率</small><strong>{number(current.score)}</strong></div></div><p className="dc-message">來源門檻：{number(current.threshold)} · 門檻尺度未確認</p><div className="dc-chart-title"><h4>測量趨勢</h4><span>來源提供的原始序列</span></div><Plot e={current}/><div className="dc-suggestion"><CheckCircle2 size={17}/><div><strong>建議檢查方向 <small>來源建議</small></strong><p>{current.suggestion??'尚未提供調查建議'}</p></div></div><p className="dc-message">訊息回覆：{predictionLabels[current.response_status??'unknown']} · 回執：{current.tester_receipt_id??'未提供'}</p><details className="dc-raw"><summary>證據識別與原始資料</summary><pre>{JSON.stringify(current,null,2)}</pre></details></>:<div className="dc-empty"><div className="dc-empty-symbol"><Layers3 size={36}/></div><h3>{data?'這個範圍尚無異常證據':'讓資料開始說話'}</h3><p>{data?'未提供告警，不代表已確認正常。':'輸入 Run ID 載入 D 的資料，或先探索離線重播。'}</p><Link href="/replay">查看重播分析 <ArrowRight size={16}/></Link></div>}</div></div></>}
 {tab==='predictions'&&<div className="dc-table-wrap" tabIndex={0} role="region" aria-label="預測紀錄表格，可水平捲動"><p>只展示來源的預測紀錄；實測只連結唯一符合範圍的紀錄。特徵完整度不是準確率。</p><table><thead><tr><th>階段 / 裝置</th><th>Site</th><th>預測 / 實測</th><th>單位</th><th>特徵完整度</th><th>回覆狀態 / 回執</th></tr></thead><tbody>{predictions.map(e=><tr key={e.event_id}><td>{e.stage}<small>{e.device_id}</small><details><summary>預測來源</summary><small>每 site 請求：{e.request_id??'未提供'}</small><small>原始請求：{e.original_request_id??'未提供'}</small><small>來源事件：{e.source_event_id??'未提供'}</small></details></td><td>{e.site_id??'—'}</td><td>{e.prediction??'未提供'} / {e.actual??'未提供'}{e.actual_status&&<small>{e.actual_status}</small>}</td><td>{e.unit??'未確認'}</td><td>{e.coverage===undefined?'未提供':`${(e.coverage*100).toFixed(0)}%`}</td><td>{predictionLabels[e.response_status??'unknown']}<small>{e.tester_receipt_id??'未提供回執'}</small></td></tr>)}</tbody></table>{!predictions.length&&<div className="dc-empty"><Clock3/><h3>尚無可展示的預測紀錄</h3></div>}</div>}
 {tab==='commands'&&<div className="dc-command-list"><p>唯讀顯示後端回報。AI 回答不會改變命令狀態。</p>{data?.commands.map(c=><article key={c.command_id}><span>{commandLabels[c.status]??c.status}</span><h3>{c.message}</h3><small>{c.command_id}</small><p>{c.tester_receipt_id?`回執參考：${c.tester_receipt_id}`:'快照未提供回執參考；此畫面無法獨立核對機台接收。'}</p></article>)}{!data?.commands.length&&<div className="dc-empty"><Unplug/><h3>尚無機台命令</h3><p>此工作台不會自動發送機台指令。</p></div>}</div>}
 </div></section><aside className="dc-ai"><div className="dc-ai-heading"><span><Sparkles size={20}/></span><div><h2>AI 調查助理</h2><small>POWERED BY OPENAI</small></div><i/></div><div className="dc-ai-context"><span>調查範圍</span><strong>{current?`W${current.wafer_id??'—'} · ${names[current.kind??'']??current.kind}`:scope?.run??'等待選取批次'}</strong></div><div className="dc-chat" aria-live="polite">{!messages.length?<div className="dc-ai-welcome"><div className="dc-orbit" aria-hidden="true"><Sparkles size={30}/></div><h3>從證據，找到答案。</h3><p>詢問異常依據、比較 site，或釐清還缺少哪些資料。回答會引用後端提供的證據。</p>{['這筆異常的依據是什麼？','比較其他 site，有哪些差異？','下一步應該檢查什麼？'].map(q=><button key={q} disabled={!scope||busy} onClick={()=>void ask(q)}>{q}<ArrowUpRight size={15}/></button>)}</div>:messages.map((m,i)=><div key={i} className={`dc-chat-message ${m.role}`}><small>{m.role==='user'?'你':'AI · 證據調查'}</small><Answer text={m.text}/>{m.refs?.length?<div className="dc-citations">{m.refs.map(id=><button key={id} onClick={()=>{const e=evidence.find(e=>e.evidence_id===id);if(e){setSelected(e.event_id);setTab('evidence');}}}>↗ {id}</button>)}</div>:null}{m.id&&<small>調查紀錄 {m.id}</small>}</div>)}{busy&&<div className="dc-thinking"><RefreshCw size={15}/>正在查詢證據與整理回答…</div>}</div>{chatError&&<div className="dc-error" role="alert">{chatError}</div>}<form className="dc-composer" onSubmit={e=>{e.preventDefault();void ask(question);}}><textarea aria-label="詢問 AI" placeholder={scope?'針對這個批次提出問題…':'載入批次後開始調查…'} value={question} onChange={e=>setQuestion(e.target.value)} maxLength={2000} disabled={!scope||busy}/><div><span>READ-ONLY INVESTIGATION</span><button className="dc-primary" aria-label="送出問題" disabled={!scope||busy||!question.trim()}><Send size={17}/></button></div></form><p className="dc-ai-foot">AI 提供調查建議，不代表機台已收到訊息。</p></aside></div>
 <footer className="dc-footer"><span><Database size={13}/>{data?`${data.run.run_id} / ${data.run.tester_id}`:'尚未取得後端資料'}{data?.run.mode==='replay'?' · 重播時間為匯入排序時間':''}{data&&` · 最後事件：${data.run.last_event_at} · 已儲存資料不代表目前機台串流`}</span><span>GRP6 · EVIDENCE BEFORE CONCLUSIONS</span></footer></main></div></div>;
}
