export type TourRoute = '/' | '/workspace' | '/sandbox';
export type TourStep = {
  id: string; route: TourRoute; chapter: string; title: string; body: string;
  target: string; tab?: string; detail?: string;
  preview?: {label: string; rows: [string, string][]};
};

export const tourSteps: TourStep[] = [
  {id:'overview',route:'/',chapter:'Replay analysis',title:'Read the source before the result',target:'.replay-banner',body:'Replay analysis reviews historical evidence. It does not establish a live tester connection or confirm receipt of a command.',detail:'This guide highlights controls without importing files, loading runs, generating fixtures or sending model requests. Next and Back may change display tabs. Cross-page steps use normal page navigation. The header language and theme controls apply across all three pages; language also applies to new answers.'},
  {id:'totals',route:'/',chapter:'Replay analysis',title:'Understand the summary',target:'.replay-overview .stats',body:'Dataset size, recorded alerts and alerted wafers describe the loaded summary. Tester receipt remains unverified unless supported by source evidence.',detail:'The animated wafer is an illustration, not a spatial wafer map. Its controls change the illustration only.'},
  {id:'filter',route:'/',chapter:'Replay analysis',title:'Filter the wafer list',target:'.wafer-panel select',tab:'.replay-tabs [role="tab"][id$="-trigger-analysis"]',body:'Choose All, With alerts or No alerts to narrow the list. No recorded alert does not establish normal operation. Filtering can change the selected wafer if it leaves the filtered set.'},
  {id:'wafer',route:'/',chapter:'Replay analysis',title:'Select a wafer and read its yield',target:'.wafer-tiles',tab:'.replay-tabs [role="tab"][id$="-trigger-analysis"]',body:'Each tile shows its source wafer ID, cumulative yield and alert count. Select a tile or use Next wafer to inspect another wafer in the current filter.',detail:'Yield is shown as a percentage. Tiles follow source order; their positions do not represent physical die locations.'},
  {id:'yield',route:'/',chapter:'Replay analysis',title:'Separate evaluation labels from observations',target:'.wafer-summary',tab:'.replay-tabs [role="tab"][id$="-trigger-analysis"]',body:'Cumulative yield describes completed devices. The dataset label is an evaluation reference, not a detector rule. Review any missed-detection note even when the alert count is zero.'},
  {id:'alerts',route:'/',chapter:'Replay analysis',title:'Inspect each recorded alert',target:'.alert-selector',tab:'.replay-tabs [role="tab"][id$="-trigger-analysis"]',body:'A wafer can contain several alerts. The alert selector opens the corresponding observed value, reference, detector score and site evidence. A detector score is not a probability.',preview:{label:'Alert reading example',rows:[['Observed / reference','2.60 / 1.12 · synthetic values'],['Detector score','5.43 · not a probability']]}},
  {id:'series',route:'/',chapter:'Replay analysis',title:'Compare the measurement sequences',target:'.replay-plot',tab:'.replay-tabs [role="tab"][id$="-trigger-analysis"]',body:'Compare site traces and their reference. The horizontal axis is sample or completed-device order, not time. Raw units remain unverified unless supplied by the source.',detail:'Source guidance is detector text, not an LLM answer. Copy handoff and source fields preserve the local wafer/alert reference; it is not a backend event ID.'},
  {id:'import',route:'/',chapter:'Replay analysis',title:'Import a different replay summary',target:'.replay-actions',body:'Import summary accepts replay JSON up to 5 MiB and validates it in browser memory. It does not upload the file or request AI analysis.',detail:'Invalid imports retain the previous dataset. Reload snapshot or leaving this page replaces an in-memory import with the bundled snapshot. The guide never activates these controls.'},
  {id:'validation',route:'/',chapter:'Replay analysis',title:'Review model validation',target:'.model-panel',tab:'.replay-tabs [role="tab"][id$="-trigger-validation"]',body:'Compare prediction error metrics with the baseline and inspect the evaluation sample count. MAE, RMSE and worst error answer different questions about error magnitude.',detail:'Dataset validation is not proof of live accuracy, latency or tester receipt. Full feature coverage does not mean perfect predictions.'},
  {id:'limitations',route:'/',chapter:'Replay analysis',title:'Read the limits before drawing conclusions',target:'.limitations-panel',tab:'.replay-tabs [role="tab"][id$="-trigger-limitations"]',body:'Source limitations, missing timestamps and live-integration notes define what this replay can support. A late alert does not prove delivery before wafer completion.',detail:'Next opens Run workspace. Tour progress follows the navigation; the guide will not load a run.'},
  {id:'load',route:'/workspace',chapter:'Run workspace',title:'Choose a run and tester scope',target:'.dc-connect',body:'Enter the Run ID and optional Tester ID, then explicitly choose Load run to request a backend snapshot. The guide leaves your current scope and inputs unchanged.',detail:'Existing conversation restoration requires a fresh valid snapshot. An unknown or ambiguous scope is an error, not an empty successful run.'},
  {id:'stream',route:'/workspace',chapter:'Run workspace',title:'Check source mode and stream status',target:'.dc-stream-status',body:'Event stream connected describes the browser’s backend stream. It does not establish a live tester connection. Read Source mode and source timestamps alongside the status.',detail:'Reconnects can retain previously loaded records. Stored data alone does not establish current connectivity.'},
  {id:'evidence',route:'/workspace',chapter:'Run workspace',title:'Search and select evidence',target:'.dc-evidence-layout',tab:'#tab-evidence',body:'Search by wafer, test or category, then select a record. Compare observed value, baseline, threshold, site traces and the original source recommendation.',detail:'Record identity and raw JSON expose provenance. Missing series remain unavailable. The guide does not change your search, selected incident or investigation draft.'},
  {id:'temperature',route:'/workspace',chapter:'Run workspace',title:'Compare Temperature predictions and actuals',target:'.dc-temperature',tab:'#tab-predictions',body:'Read predicted and uniquely matched actual values by stage and site. Difference is predicted minus actual. Missing or conflicting actuals do not become zero.',detail:'Expand Device & provenance for request IDs, feature coverage and receipt status. Source units may be unconfirmed; no acceptance tolerance is assumed.',preview:{label:'Temperature comparison example',rows:[['Stage / site','Stage 2 · Site 1'],['Predicted / actual','42.3 / 41.8 · synthetic units'],['Difference','+0.5 · no pass/fail claim']]}},
  {id:'commands',route:'/workspace',chapter:'Run workspace',title:'Distinguish queued commands from receipts',target:'.dc-command-list',tab:'#tab-commands',body:'This view is read-only. Queued, edge received and queued to tester are different from tester confirmed. Rejected, failed and expired states remain meaningful outcomes.',detail:'Even a displayed confirmation is a backend report requiring correlated evidence for live acceptance. The guide and investigation tools send no tester commands.'},
  {id:'investigate',route:'/workspace',chapter:'Run workspace',title:'Draft an evidence-linked investigation',target:'.dc-ai-context',body:'The investigation context follows the resolved run, tester and incident. Question templates create drafts only. Review the selected evidence before submitting.',detail:'The guide does not select templates, edit questions or submit requests. Service-unavailable states remain visible when model or backend configuration is missing. Semiconductor Q&A explains general concepts from local references without accessing the selected run.'},
  {id:'cost',route:'/workspace',chapter:'Run workspace',title:'Understand model cost and saved answers',target:'.dc-composer',body:'Submit explicitly sends a model API request and can incur cost. Completed answers, evidence references and traces are stored by the service. Generated analysis is advisory.',detail:'Browser-tab conversation and draft restoration is scoped to run/tester/incident. It is not cross-device history. Earlier saved answers remain unchanged; citations must refer to evidence from the current scope.'},
  {id:'sandbox',route:'/sandbox',chapter:'Sandbox',title:'Experiment with explicitly synthetic data',target:'.simulation-banner',body:'Sandbox fixtures are synthetic and have no live tester connection. They demonstrate event handling, evidence and response semantics without proving machine performance.',detail:'This guide does not receive a fixture or alter an existing sandbox workspace.'},
  {id:'fixtures',route:'/sandbox',chapter:'Sandbox',title:'Choose a fixture scenario',target:'.receive-controls',body:'Mean shift, Normal fixture and Missing data exercise different states. Repeat previous batch demonstrates deduplication. Receive fixture is an explicit local action.',preview:{label:'Fixture example',rows:[['Scenario','Synthetic mean shift'],['Receipt','Not supplied · no tester connection']]}},
  {id:'sandbox-evidence',route:'/sandbox',chapter:'Sandbox',title:'Inspect events, predictions and JSON',target:'.event-tabs',tab:'.event-tabs [role="tab"][id$="-trigger-evidence"]',body:'Event analysis presents source evidence. Temperature predictions separate predictions from actuals. Message JSON accepts supported batches with validation and deduplication.',detail:'A valid batch is not proof of physical units or tester receipt. Reset workspace clears local data only; the guide never invokes it.'},
  {id:'rule-demo',route:'/sandbox',chapter:'Sandbox',title:'Distinguish rule-based and model analysis',target:'.ai-toolbar',body:'Rule-based analysis uses predefined responses and makes no model API call. OpenAI API mode sends the selected event and that mode’s conversation when you explicitly submit.',detail:'The guide never changes the response mode or sends a request. An unavailable OpenAI service does not silently turn an API response into a rule-based answer.'},
  {id:'finish',route:'/sandbox',chapter:'Sandbox',title:'Continue with the evidence',target:'.composer',body:'Select a question to draft it, review the context, and submit only when intended. Source claims, model suggestions and confirmed tester receipts remain distinct.',detail:'Finish closes the guide and returns keyboard focus to Guide. You can reopen any chapter from the shared header.'},
];

export function tourRoute(path: string): TourRoute | null {
  const clean = path.endsWith('/') && path !== '/' ? path.slice(0, -1) : path;
  return clean === '/replay' ? '/' : clean === '/' || clean === '/workspace' || clean === '/sandbox' ? clean : null;
}
