"use client";
import {ThemeSelector} from '@/components/theme-controls';
import { z } from "zod";
import { useCallback,useEffect,useRef,useState } from "react";
import { Activity, ArrowUpRight, Bell, Check, ChevronRight, CircleDashed, ClipboardList, Copy, Cpu, FileJson2, FlaskConical, Info, LoaderCircle, Radio, RotateCcw, Send, TriangleAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { NativeSelect,NativeSelectOption } from "@/components/ui/native-select";
import { Tabs,TabsList,TabsTrigger,TabsContent } from "@/components/ui/tabs";
import { Alert,AlertDescription } from "@/components/ui/alert";
import { batchSchema,emptyWorkspace,receiveBatch,type EvidenceRecord,type EventView,type Workspace } from "@/lib/rtdi/contracts";
import { adaptIncoming } from "@/lib/rtdi/edge-adapter";
import { createFixture,scenarioLabels,type Scenario } from "@/lib/rtdi/fixtures";
import type { ChatMessage } from "@/lib/rtdi/assistant";

type Reply=ChatMessage&{mode?:"demo"|"openai";model?:string|null};
const kindLabels={normal:"Normal observation",mean_drift:"Mean shift",low_yield:"Low yield",missing_data:"Insufficient data",measurement:"Measurement",prediction:"Prediction",external_evidence:"External alert evidence",heartbeat:"Edge heartbeat",run_summary:"Wafer summary"};
const modeLabels={simulation:"Synthetic fixture",replay:"Replay",live:"Source marked live · unverified"};
const responseLabels={unknown:"Unverified",not_requested:"Not requested",insufficient_data:"Missing data",response_queued:"Response queued",tester_confirmed:"Receipt supplied"};
const scenarioDisplayLabels:Record<Scenario,string>={anomaly:"Mean shift",normal:"Normal fixture",missing:"Missing data",duplicate:"Repeat previous batch"};
const prompts=["What does this alert indicate?","What should be checked next?","Is tester receipt confirmed (ACK)?"];
function timeOf(stamp:string){return new Date(stamp).toLocaleTimeString("en-US",{hour12:false,hour:"2-digit",minute:"2-digit",second:"2-digit",timeZone:"Asia/Taipei"});}
function Trend({evidence:e}: {evidence:EvidenceRecord}){
 const sites=Object.entries(e.site_series??{}).filter(([,values])=>values.length);
 const lines=e.metric!=='yield'&&sites.length?sites.map(([site,values])=>({label:`Site ${site}`,points:values.map((value,index)=>({index:index+1,value}))})):[{label:'Observed',points:e.series}];
 const points=lines.flatMap(line=>line.points);
 if(!points.length)return <div className="no-chart"><CircleDashed size={30}/><strong>No sequence supplied</strong><span>Missing values are unavailable, not zero or evidence of normal operation.</span></div>;
 const vals=[...points.map(p=>p.value),...(e.baseline===null?[]:[e.baseline])];
 const low=Math.min(...vals),high=Math.max(...vals),pad=Math.max((high-low)*.17,.01),min=low-pad,max=high+pad;
 const count=Math.max(...lines.map(line=>line.points.length));
 const y=(v:number)=>190-(v-min)/(max-min)*155;const x=(i:number)=>53+i/Math.max(count-1,1)*567;
 const colors=['var(--chart-1)','var(--chart-2)','var(--chart-3)','var(--chart-4)'];
 const valueLabel=(value:number)=>e.metric==='yield'?`${(value*100).toFixed(1)}%`:value.toFixed(2);
 return <div className="trend"><div className="chart-title"><span>Measurement sequence <small>{e.metric==='yield'?'Yield %':e.unit}</small></span><div className="legend">{lines.map((line,i)=><span key={line.label}><i style={{borderColor:colors[i%colors.length]}}/>{line.label}</span>)}</div></div><svg viewBox="0 0 650 235" role="img" aria-label="Source sequence; x-axis is completed-device order, not time">
 {[0,1,2,3].map(i=>{const v=min+(max-min)*i/3;return <g key={i}><path d={`M53 ${y(v)}H620`} stroke="var(--border)"/><text x="40" y={y(v)+4} textAnchor="end">{valueLabel(v)}</text></g>})}
 {e.baseline!==null&&<path d={`M53 ${y(e.baseline)}H620`} stroke="var(--muted-foreground)" strokeDasharray="5 5"/>}
 {lines.map((line,i)=><path key={line.label} d={line.points.map((p,j)=>`${j?'L':'M'} ${x(j)} ${y(p.value)}`).join(' ')} fill="none" stroke={colors[i%colors.length]} strokeWidth="2.6" strokeLinejoin="round"/>)}
 {[0,Math.floor((count-1)/2),count-1].map((i,k)=><text key={k} x={x(i)} y="214" textAnchor="middle">{lines[0].points[i]?.index??i+1}</text>)}<text x="620" y="232" textAnchor="end">{sites.length&&e.metric!=='yield'?'Completed-device order within each site':'Completed-device order'}</text>
 </svg></div>;
}
export default function Home(){
 const [workspace,setWorkspace]=useState<Workspace>(emptyWorkspace);const stateRef=useRef(workspace);
 const [selected,setSelected]=useState<string|null>(null);const [scenario,setScenario]=useState<Scenario>("anomaly");const seq=useRef(0);
 const [notice,setNotice]=useState("");const [inputError,setInputError]=useState("");const [raw,setRaw]=useState("");
 const [aiMode,setAiMode]=useState<"demo"|"openai">("demo");const [config,setConfig]=useState<{openai_configured:boolean;model:string}|null>(null);
 const [configError,setConfigError]=useState(false);const [chats,setChats]=useState<Record<string,Reply[]>>({});const [question,setQuestion]=useState("");
 const [busy,setBusy]=useState(false);const busyRef=useRef(false);const pending=useRef<AbortController|null>(null);const [aiError,setAiError]=useState("");const [copied,setCopied]=useState(false);const copySeq=useRef(0);
 const current=workspace.items.find(i=>i.event.event_id===selected)??workspace.items[0];const currentId=current?.event.event_id;
 const threadKey=currentId?`${currentId}:${aiMode}`:"";const replies=chats[threadKey]??[];const chatEnd=useRef<HTMLDivElement>(null);
 const cancelInvestigation=useCallback(()=>{pending.current?.abort();pending.current=null;busyRef.current=false;setBusy(false);},[]);
 const accept=useCallback((input:unknown)=>{
  try{const previous=stateRef.current;const batch=adaptIncoming(input,previous);const next=receiveBatch(previous,batch);cancelInvestigation();stateRef.current=next;setWorkspace(next);copySeq.current++;setCopied(false);
   const event=batch.records.find(r=>r.type==="event");if(event)setSelected(event.event_id);
   const duplicates=next.duplicateCount-previous.duplicateCount;
   setNotice(duplicates?`Ignored ${duplicates} duplicate events; no duplicate incidents created.`:`Batch received; ${next.items.length} unique events in this workspace.`);setInputError("");return next;
  }catch(error){setInputError(error instanceof Error&&!("issues" in error)?error.message:"Invalid event batch. Check schema_version, records, timestamps and required fields.");throw error;}
 },[cancelInvestigation]);
 const simulate=useCallback((kind:Scenario)=>{
   const last=stateRef.current.batches.at(-1);if(kind==="duplicate"&&!last){setInputError("Receive a batch before testing duplicate delivery.");return;}
   const batch=kind==="duplicate"?last!:createFixture(kind,++seq.current);accept(batch);
 },[accept]);
 useEffect(()=>{const controller=new AbortController();fetch("/api/config",{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>setConfig(z.object({openai_configured:z.boolean(),model:z.string()}).parse(data))).catch(e=>{if(e.name!=="AbortError")setConfigError(true);});return()=>controller.abort();},[]);
 useEffect(()=>{
  const listener=(event:Event)=>{try{accept((event as CustomEvent).detail);}catch{/* visible validation error */}};
  window.addEventListener("rtdi:batch",listener);return()=>window.removeEventListener("rtdi:batch",listener);
 },[accept]);
 useEffect(()=>{chatEnd.current?.scrollIntoView({block:"nearest",behavior:"smooth"});},[replies.length,busy]);
 useEffect(()=>{cancelInvestigation();setQuestion("");setAiError("");},[currentId,aiMode,cancelInvestigation]);
 useEffect(()=>()=>{pending.current?.abort();pending.current=null;copySeq.current++;},[]);
 // Optional WebMCP: same validated input and state as the visible JSON receiver.
 useEffect(()=>{
  type ModelContext={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>Promise<unknown>},options:{signal:AbortSignal})=>void|Promise<void>};
  const context=(document as Document&{modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;
  const lifetime=new AbortController();
  void Promise.resolve(context.registerTool({name:"receive_rtdi_demo_batch",description:"Receive a synthetic RTDI batch in the visible prototype. Never sends machine commands or calls OpenAI.",inputSchema:{type:"object",properties:{scenario:{type:"string",enum:["anomaly","normal","missing","duplicate"]}},required:["scenario"],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input){
    const value=input as {scenario?:Scenario};if(!value||Object.keys(value).length!==1||!Object.keys(scenarioLabels).includes(value.scenario??""))throw Error("Invalid scenario");
    if(value.scenario==="duplicate"&&!stateRef.current.batches.length)throw Error("No previous batch");simulate(value.scenario!);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {event_count:stateRef.current.items.length,duplicate_count:stateRef.current.duplicateCount};
  }},{signal:lifetime.signal})).catch(()=>{});return()=>lifetime.abort();
 },[simulate]);
 async function ask(text:string){
   if(!current||!text.trim()||busyRef.current||(aiMode==='openai'&&!config?.openai_configured))return;const sent=text.trim();const context=current;const key=threadKey;const history=replies.slice(-10).map(({role,content})=>({role,content}));
   const controller=new AbortController();pending.current=controller;busyRef.current=true;setBusy(true);setAiError("");setQuestion("");
   try{const response=await fetch("/api/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:aiMode,question:sent,context,history}),signal:controller.signal});
    const payload=await response.json();if(pending.current!==controller||controller.signal.aborted)return;if(!response.ok){const failure=z.object({error:z.string()}).safeParse(payload);throw Error(failure.success?failure.data.error:"No answer returned. Retry the request.");}
    const data=z.object({answer:z.string(),mode:z.enum(["demo","openai"]),model:z.string().nullable()}).parse(payload);
    setChats(prev=>({...prev,[key]:[...(prev[key]??[]),{role:"user",content:sent},{role:"assistant",content:data.answer,mode:data.mode,model:data.model}]}));
   }catch(error){if(pending.current===controller&&!controller.signal.aborted&&error instanceof Error&&error.name!=="AbortError"){setAiError(error.message);setQuestion(sent);}}
   finally{if(pending.current===controller){pending.current=null;busyRef.current=false;setBusy(false);}}
 }
 function reset(){copySeq.current++;setCopied(false);cancelInvestigation();const fresh=emptyWorkspace();stateRef.current=fresh;setWorkspace(fresh);setSelected(null);setChats({});setAiError("");setInputError("");setQuestion("");setNotice("Local workspace cleared. Tester data is unchanged.");}
 const aiUnavailable=aiMode==='openai'&&!config?.openai_configured;
 const e=current?.evidence[0];const anomalies=new Set(workspace.items.map(i=>i.event.incident_id).filter(Boolean)).size;
 return <div className="shell"><header className="topbar"><a className="brand" href="/"><span className="brandmark"><Activity size={22}/></span> RTDI <span className="brandlight">Insight</span></a><div className="header-right"><ThemeSelector/><a className="mode" href="/replay"><Activity size={14}/> Replay analysis</a><span className="mode"><FlaskConical size={14}/> Local sandbox</span><span className="team">G6</span></div></header>
 <main className="workspace"><div className="heading"><div><div className="eyebrow">GRP6 / EVENT SANDBOX</div><h1>Event sandbox</h1><p className="sub">Validate event batches, inspect evidence and test investigation requests.</p></div><div className="receive-controls"><NativeSelect aria-label="Fixture scenario" value={scenario} onChange={ev=>setScenario(ev.target.value as Scenario)}>{Object.entries(scenarioDisplayLabels).map(([k,v])=><NativeSelectOption value={k} key={k}>{v}</NativeSelectOption>)}</NativeSelect><Button className="primary-action" onClick={()=>simulate(scenario)}><Radio size={17}/> Receive fixture <ArrowUpRight size={16}/></Button></div></div>
 <div className="simulation-banner"><FlaskConical size={16}/><span>Built-in scenarios use synthetic data. This sandbox has no live tester connection; assistant responses do not prove tester receipt.</span><span className="banner-end">SIMULATION MODE</span></div>
 <div className="stats"><div><span>Input source</span><strong>Local <small>events</small></strong><p>Browser workspace</p></div><div><span>Unique events</span><strong>{String(workspace.items.length).padStart(2,"0")} <small>events</small></strong><p>{workspace.duplicateCount?`${workspace.duplicateCount} duplicates ignored`:'Current browser session'}</p></div><div><span>Tagged incidents</span><strong className="orange">{String(anomalies).padStart(2,"0")}</strong><p>{anomalies?'Counted from source incident IDs':'No tagged incidents'}</p></div><div><span>Investigation service</span><strong>OpenAI</strong><p>{configError?'Configuration check failed':config?.openai_configured?'Configured · model call unverified':config?'Unconfigured · rule-based mode available':'Checking configuration…'}</p></div></div>
 <div className="status-row"><span role="status" aria-live="polite">{notice||'Select a fixture scenario to receive the first event.'}</span><Button variant="ghost" size="sm" onClick={reset} disabled={!workspace.items.length&&!inputError}><RotateCcw size={13}/> Reset workspace</Button></div>
 {inputError&&<Alert variant="destructive" className="inline-error"><TriangleAlert/><AlertDescription>{inputError}</AlertDescription></Alert>}
 <div className="work-grid"><section className="panel evidence-panel"><div className="panel-header"><h2><Activity size={18}/> Events & evidence</h2><span className="mini-label">EVENT WORKSPACE</span></div>
 <Tabs defaultValue="evidence" className="event-tabs"><TabsList variant="line" aria-label="Event views"><TabsTrigger value="evidence">Event analysis</TabsTrigger><TabsTrigger value="predictions">Temperature predictions</TabsTrigger><TabsTrigger value="message">Message JSON</TabsTrigger></TabsList>
 <TabsContent value="evidence">{!current?<div className="empty"><div className="empty-icon"><Radio size={30}/></div><h3>No events loaded</h3><p>Receive a synthetic fixture or paste a supported JSON batch.</p><Button variant="outline" onClick={()=>simulate("anomaly")}>Receive fixture <ArrowUpRight size={16}/></Button></div>:<div className="event-body">
 <div className={`event-badge ${current.event.kind==='normal'?'normal-badge':current.event.kind==='missing_data'?'missing-badge':''}`}>{current.event.kind==='normal'?<Check size={14}/>:<TriangleAlert size={14}/>} {kindLabels[current.event.kind]}<span>· {modeLabels[current.event.mode]}</span></div>
 <h2>{current.incident?.title??kindLabels[current.event.kind]}</h2><p className="event-message">{current.event.message}</p>
 <div className="event-meta"><span>{current.event.wafer_id}</span><span>Site {current.event.site??'All'}</span><span>{timeOf(current.event.occurred_at)} UTC+8</span></div>
 {e?<><div className="evidence-metrics"><div><span>{e.metric==='yield'?'Yield':e.metric==='coverage'?'Feature coverage':e.metric==='measurement'?'Observed':'Window mean'}</span><strong>{e.observed===null?'—':(e.metric==='coverage'||e.metric==='yield')?`${(e.observed*100).toFixed(1)}%`:e.observed.toFixed(4)}<small>{(e.metric==='coverage'||e.metric==='yield')?'':e.unit}</small></strong></div><div><span>Reference baseline</span><strong>{e.baseline===null?'—':e.metric==='yield'?`${(e.baseline*100).toFixed(1)}%`:e.baseline}</strong></div><div><span>Samples</span><strong>{e.sample_count}<small>samples</small></strong></div></div><Trend evidence={e}/><div className="evidence-foot"><span>{e.test_name}</span><span>Evidence · {e.evidence_id}</span><span>Source threshold: {e.threshold??'Not provided'} · scale unverified</span>{e.response_status&&<span>Response: {responseLabels[e.response_status]} · Receipt: {e.tester_receipt_id??'Not provided'}</span>}</div>{e.missing_fields.length>0&&<div className="missing-fields"><Info size={15}/><span>Missing: {e.missing_fields.join(', ')}</span></div>}</>:<div className="no-chart"><Info/><strong>No matching evidence</strong><span>A message alone cannot establish root cause. Matching evidence is required.</span></div>}
 <div className="delivery"><div><Bell size={15}/><strong>Tester delivery</strong><span>No command created</span></div><div className="delivery-steps" style={{flexWrap:"wrap"}}><span>Draft</span><ChevronRight/><span>Backend queue</span><ChevronRight/><span>Edge receipt</span><ChevronRight/><span>Tester queue</span><ChevronRight/><span>Tester receipt</span></div><p>This sandbox does not send tester commands. Assistant answers do not change delivery status.</p></div>
 </div>}</TabsContent>
 <TabsContent value="predictions"><div className="prediction-body"><div className="section-title"><h3>Six-stage temperature predictions</h3><span>Selected event only</span></div><p className="sub">Fixture values do not establish model accuracy or physical units. A queued response is not tester confirmation.</p>{current?.predictions.length?<div className="table-scroll"><table><thead><tr><th>Stage</th><th>Predicted / actual</th><th>Coverage</th><th>Response status</th></tr></thead><tbody>{current.predictions.map(p=><tr key={p.prediction_id}><td><span className="stage-number">0{p.stage}</span><details><summary>Prediction provenance</summary><small>Per-site request: {p.request_id??'Not provided'}</small><small>Original request: {p.original_request_id??'Not provided'}</small><small>Source event: {p.source_event_id??'Not provided'}</small></details></td><td><strong>{p.predicted?.toFixed(2)??'—'}</strong><span className="actual"> / {p.actual?.toFixed(2)??'—'}</span><small>{p.unit}</small></td><td>{p.coverage===null?'Unknown':`${Math.round(p.coverage*100)}%`}</td><td><span className={`prediction-status ${p.response_status==='insufficient_data'?'orange':''}`}>{responseLabels[p.response_status]}</span>{p.tester_receipt_id&&<small>{p.tester_receipt_id}</small>}</td></tr>)}</tbody></table></div>:<div className="no-chart"><Cpu/><strong>No predictions supplied</strong><span>Receive an event batch to inspect its associated predictions.</span></div>}</div></TabsContent>
 <TabsContent value="message"><div className="json-body"><div className="section-title"><h3>Receive event batch</h3><span>Draft interface v0.1</span></div><p className="sub">Paste a supported event batch. Validation and deduplication run before updating this browser workspace.</p><label htmlFor="batch-json" className="field-label">Message JSON</label><Textarea id="batch-json" className="json-editor" value={raw} onChange={ev=>setRaw(ev.target.value)} placeholder={'{"schema_version":"0.1-draft","batch_id":"...","sent_at":"...","records":[...]}'} spellCheck={false}/><div className="json-actions"><Button variant="outline" onClick={()=>setRaw(JSON.stringify(createFixture("anomaly",++seq.current),null,2))}><FileJson2 size={15}/> Load fixture</Button><Button onClick={()=>{try{accept(JSON.parse(raw));}catch(error){if(error instanceof SyntaxError)setInputError("Invalid JSON syntax. Check braces, quotes and commas.");}}} disabled={!raw.trim()}><Radio size={15}/> Receive JSON</Button></div>{current&&<details className="raw-details"><summary>View source event fields</summary><pre>{JSON.stringify(current,null,2)}</pre><Button variant="ghost" size="sm" onClick={async()=>{const request=++copySeq.current;setCopied(false);try{await navigator.clipboard.writeText(JSON.stringify(current,null,2));if(request===copySeq.current)setCopied(true);}catch{if(request===copySeq.current)setNotice("Clipboard unavailable. Select the source text to copy manually.");}}}>{copied?<Check size={14}/>:<Copy size={14}/>} {copied?'Copied':'Copy source'}</Button></details>}</div></TabsContent></Tabs>
 {workspace.items.length>0&&<div className="event-inbox"><div className="section-title"><h3>Received events</h3><span>{workspace.items.length} unique events</span></div><div className="inbox-list">{workspace.items.map(item=><button key={item.event.event_id} className={`inbox-item ${item.event.event_id===currentId?'selected':''}`} onClick={()=>{cancelInvestigation();setSelected(item.event.event_id);setAiError("");setQuestion("");copySeq.current++;setCopied(false);}} aria-pressed={item.event.event_id===currentId}><span className={`inbox-symbol ${item.event.kind==='normal'?'normal':''}`}>{item.event.kind==='normal'?<Check size={15}/>:<Activity size={15}/>}</span><span><strong>{kindLabels[item.event.kind]}</strong><small>{item.event.wafer_id} · Site {item.event.site}</small></span><time>{timeOf(item.event.occurred_at)}</time><ChevronRight size={14}/></button>)}</div></div>}
 </section>
 <aside className="panel ai-panel"><div className="panel-header"><h2><ClipboardList size={18}/> Investigation log</h2><span className="assistant-label">EVENT CONTEXT</span></div><div className="ai-toolbar"><NativeSelect value={aiMode} aria-label="Response mode" onChange={ev=>{cancelInvestigation();setAiMode(ev.target.value as "demo"|"openai");setAiError("");}} disabled={busy}><NativeSelectOption value="demo">Rule-based analysis</NativeSelectOption><NativeSelectOption value="openai">OpenAI API</NativeSelectOption></NativeSelect><span>{aiMode==='demo'?'No model API call':config?.openai_configured?'Configured':'Unconfigured'}</span></div>
 <div className="sandbox-service" role="status">{aiUnavailable?'OpenAI is unavailable. Use rule-based analysis or reload after the service is configured.':aiMode==='demo'?'Rule-based fixture analysis. No model API call.':'Submitting a question sends a request to OpenAI.'}</div><div className="chat-scroll" aria-live="polite">{!replies.length?<div className="assistant-intro"><h3>{current?'Selected event analysis':'No event selected'}</h3><p>{current?'Review observed values, possible causes and checks using the selected event evidence.':'Receive an event to enable analysis. Missing evidence limits the conclusions available.'}</p>{current&&<div className="context-card"><span>Selected context</span><strong>{kindLabels[current.event.kind]} · Site {current.event.site}</strong><small>{current.event.event_id}</small></div>}<div className="suggestions"><p>Draft only · Select a question, review it, then submit.</p>{prompts.map(p=><Button key={p} type="button" variant="outline" disabled={!current||busy||aiUnavailable} onClick={()=>{setQuestion(p);setAiError("");}}>{p}<ClipboardList size={14}/></Button>)}</div><div className="ai-note"><Info size={14}/><span>{aiMode==='demo'?'Rule-based responses are predefined, not generated by an LLM.':'Submitting sends the selected event and this mode’s conversation to OpenAI.'}</span></div></div>:<div className="messages">{replies.map((reply,i)=><div key={i} className={`chat-message ${reply.role}`}><div className="message-author">{reply.role==='assistant'?<ClipboardList size={13}/>:null}{reply.role==='user'?'You':reply.mode==='demo'?'Rule-based analysis':`OpenAI · ${reply.model}`}</div><div className="message-text">{reply.content}</div></div>)}</div>}{busy&&<div className="thinking"><LoaderCircle size={15} className="spin"/> Analyzing selected event evidence…</div>}<div ref={chatEnd}/></div>
 {aiError&&<Alert variant="destructive" className="ai-error"><TriangleAlert/><AlertDescription>{aiError}</AlertDescription></Alert>}
 <form className="composer" onSubmit={ev=>{ev.preventDefault();void ask(question);}}><Textarea aria-label="Investigation question" placeholder={current?'Ask about this event, for example: What evidence is missing?':'Receive an event to enable questions…'} value={question} onChange={ev=>setQuestion(ev.target.value)} disabled={!current||busy||aiUnavailable} maxLength={2000} onKeyDown={ev=>{if(ev.key==='Enter'&&!ev.shiftKey&&!ev.nativeEvent.isComposing){ev.preventDefault();void ask(question);}}}/><div className="composer-footer"><span>{aiMode==='demo'?'Rule-based mode · no OpenAI call':'OpenAI Responses API'}</span><Button type="submit" size="icon" disabled={!current||busy||aiUnavailable||!question.trim()} aria-label="Submit question">{busy?<LoaderCircle className="spin" size={16}/>:<Send size={16}/>}</Button></div></form>
 </aside></div><footer><span><Bell size={13}/> Tester command and receipt transport is not connected</span><span>RTDI Insight · grp6 / Local sandbox</span></footer></main></div>;
}
